version: "3"
services: 
  mongo:
      container_name: mongo
      restart: always
      image: mongo
      volumes:
        - ./db:/data/db
      ports:
        - "27017:27017"
  blog:
      container_name: blog
      restart: always
      build: .
      ports:
        - "3000:3000"
     
    
